// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeaoOPv1zCjvDEmtShrenXXoKO0RZJF_g',
    appId: '1:999846872581:web:b801d9d15daccc9156be6c',
    messagingSenderId: '999846872581',
    projectId: 'acadobs-c32a5',
    authDomain: 'acadobs-c32a5.firebaseapp.com',
    storageBucket: 'acadobs-c32a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPimuR-1RZmbb_irKusfA1XwLkqJcp6U',
    appId: '1:999846872581:android:839af38ee284756d56be6c',
    messagingSenderId: '999846872581',
    projectId: 'acadobs-c32a5',
    storageBucket: 'acadobs-c32a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYg7Lp0HR-N5TOPamZLcAjsIxrpbPosNc',
    appId: '1:999846872581:ios:36a854beb7bd279156be6c',
    messagingSenderId: '999846872581',
    projectId: 'acadobs-c32a5',
    storageBucket: 'acadobs-c32a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProviderTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYg7Lp0HR-N5TOPamZLcAjsIxrpbPosNc',
    appId: '1:999846872581:ios:36a854beb7bd279156be6c',
    messagingSenderId: '999846872581',
    projectId: 'acadobs-c32a5',
    storageBucket: 'acadobs-c32a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProviderTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeaoOPv1zCjvDEmtShrenXXoKO0RZJF_g',
    appId: '1:999846872581:web:f02aae72231cb75756be6c',
    messagingSenderId: '999846872581',
    projectId: 'acadobs-c32a5',
    authDomain: 'acadobs-c32a5.firebaseapp.com',
    storageBucket: 'acadobs-c32a5.firebasestorage.app',
  );
}
